using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;

public class HandController : MonoBehaviour {
    [SerializeField]
    private SkinnedMeshRenderer mesh;
    [SerializeField]
    private InputActionProperty triggerAction;
    [SerializeField]
    private InputActionProperty gripAction;

    private Animator anim;

    void Start() {
        anim = GetComponent<Animator>();
    }

    void Update() {
        float triggerValue = triggerAction.action.ReadValue<float>();
        float gripValue = gripAction.action.ReadValue<float>();
        anim.SetFloat("Trigger", triggerValue);
        anim.SetFloat("Grip", gripValue);
    }
}
